spring.application.name=JWTAuthService

spring.datasource.url=jdbc:mysql://localhost:3306/auth_service
spring.datasource.username=root
spring.datasource.password=India@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
