package com.jwt.auth.audit;

public enum AuditEventType {
  
	LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_BLOCKED,
    ACCOUNT_LOCKED,
    RATE_LIMIT_BLOCKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    LOGOUT, 
    ACCESS_USER_DASHBOARD, 
    TOKEN_ACCESS, 
    AUDIT_LOG_VIEWED, 
    ACCESS_ADMIN_DASHBOARD
	
}
